name: dalui
description: "Datastore Local User Interface"
publish_to: 'none'
version: 0.0.1+local

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.2.0
  provider: ^6.1.5
  auto_route: ^10.1.0+1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.0
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true
